name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  release:
    types: 
     - published
     - prereleased

jobs:
  build-amd64:
    runs-on: ubuntu-20.04
    container: ubuntu:22.04

    steps:
    - name: Setup APT
      run:  echo 'APT::Acquire::Retries "4";' > /etc/apt/apt.conf.d/80-retries
    
    - name: Run APT updates
      run: |
        apt update
        apt upgrade -y git

    - uses: actions/checkout@v2
      with:
        ref: 'master'
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PATH"
        echo 'tzdata tzdata/Areas select Europe' | debconf-set-selections
        echo 'tzdata tzdata/Zones/Europe select Paris' | debconf-set-selections
        DEBIAN_FRONTEND="noninteractive" apt install -y libarchive-dev tree make gcc g++ lftp pkg-config qtbase5-private-dev qtbase5-dev libqt5svg5-dev libglibmm-2.4-dev libglib2.0-dev
      
    - name: Initialize project
      run: qmake geq2imp.pro "CONFIG += CI"
      
    - name: Build
      run: |
        make
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: geq2imp_binary_ubuntu22.04_linux64
        path: src/geq2imp
    
